### ISSUE TITLE
DLP policy tips

### ISSUE THREAD

**Issue by awillslo** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#127]
# Module: 05
#### Step: 00
![Hollyemail](https://user-images.githubusercontent.com/23704446/187572732-f6087477-4ffd-4658-94cb-de2c08c839d6.JPG)

Description of issue
Policy tips work just fine.

Just went through the steps for the above mentioned exercise. The policy tips work.  Even tested with 'custom tip'.

The previous lab, mentioned in the lab step note below, did NOT turn on policy tips in the Mail Flow rules, they both were marked Enforced.   So that means that DLP in Purview policy tips will work just fine.  It is noted that IF policy tips in mail flow rules are turned on, then Purview DLP Policy tips will not work.  See link. https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#policy-tips-in-the-exchange-admin-center-vs-the-microsoft-purview-compliance-portal

Important note in exercise is not valid.

**Important: Unfortunately, you will be unable to test the policy tips in this task. As was mentioned in the prior exercise, when you use the Microsoft 365 compliance center to create a DLP policy that contains a policy tip, the policy tip will NOT be displayed if you also created mail flow rules in the Exchange admin center. If you will recall, back in Module 4, Lab 4, Exercise 1, you created a mail flow transport rule in the Exchange admin center. As a result, the policy tips that you configured for DLP policies in the Microsoft 365 compliance center will NOT work. The DLP policy will work, but the policy tip will not be displayed. Even if you delete the mail transport rules, the policy tips will still not function.

Therefore, when you send an email with two IP addresses in this task, all you can do is verify that the email message is blocked. The policy tip will not display; therefore, you will be unable to override the blockage and send the email. While we wanted you to experience creating mail transport rules in the earlier lab, we also knew this would not allow you to see policy tips in this lab. But it was felt that learning how to create mail transport rules in the earlier lab was worth this minor inconvenience in this lab**.

**Comment by tfrink** [comment]
Thank you for your feedback. We are testing labs now and will verify your findings. We're releasing an updated version of MS-100 and 101 on Oct 7th, and that will include labs updates. We're in the process of reviewing the labs now. Thanks again!

**Comment by tfrink** [comment]
Just wanted to follow up after our testing. We were able to confirm your findings, so we have updated the lab steps and removed the Important note. Thank you so much for bringing this to our attention!!
