### ISSUE TITLE
Modue 11 - Lab 10 (ALL EXERCISES)

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#15]
# Module: 11
#### Step: 00

Description of issue

The Azure (Intune) Portal no longer hosts Intune - the endpoint manager portal (https://endpoint.microsoft.com) does so ALL of these exercises in Module 11 Lab 10 are now in need of a complete rewrite.

Repro steps:

1.
1.
1.

**Comment by edbakermct** [comment]
This has been open since May - does ANYONE look at this repository?

**Comment by geschwei** [comment]
Hi Ed, I am currently working through the MS-101 labs and will be reviewing and making changes. thank you for your post.

**Comment by edbakermct** [comment]
Thanks George - didn't realise the maintenance was down to the content team... that's a lot of work shout if you need help with it

**Comment by geschwei** [comment]
Thanks, Ed if something comes up I'll be sure to let you know.
