### ISSUE TITLE
Lab Instructions are  different from UI of Microsoft Portal

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#154]
# Learning Path 10 - Lab 8 - Exercise 5 - Manage and Monitor a Device in Intune
#### Step: 7

There are some specific topics where the instructions displayed on the portal differ due to updates in Microsoft portals. For example, the Azure Active Directory management portal is now integrated within the Microsoft Enter portal.
For instance, to access Microsoft Intune, the access has changed to:

![image](https://user-images.githubusercontent.com/52242119/235222723-05d7cb81-4682-4aa9-afe4-9ba1ce576f66.png)

This needs to be fixed for seamless user experience.

**Comment by sehrish777** [comment]
There is also some discrepancy between the licenses assigned to users and what the instructions say:
![image](https://user-images.githubusercontent.com/52242119/235223596-5fa1a19d-aacf-44c4-b706-703ab7f4db54.png)

**Comment by tfrink** [comment]
Thank you for bringing this to our attention. We will be releasing updates to the MS-101 lab instructions shortly due to UI changes such as the ones you found.

**Comment by sehrish777** [comment]
Thanks, there have been some issues when working on "New-TransportRule" and when using powershell commands. The instructions ask to add Holy as global admin, but that does work and creates hurdles in powershell commands. 


My suggestion is to make Holly as global admin and also the exchange admin. We tried this and the next steps worked just fine. 

Let me know if you need alternate steps from me, that I have tried and worked fine.

**Comment by tfrink** [comment]
Another user just contacted us about this same issue. However, they brought up the fact that the authentication method used in this task (basically steps 4-14) was being deprecated. We confirmed their finding and updated the task as follows:

- We basically replaced steps 4-14 with instructions on how to install and connect to the Exchange Online PowerShell module (ExchangeOnlineManagement). 
- We then ran the command in the old step 15, but modified the final parameter. The command now reads:

New-TransportRule -Name "Encrypt rule for Guest Services" -SentTo "[Gservices@adatum.com](mailto:Gservices@adatum.com)" -SentToScope "NotinOrganization" -ApplyRightsProtectionTemplate Encrypt

Originally, we ran the command with the ApplyOME property. While this worked, PowerShell returned a message indicating the ApplyOME property was being deprecated in favor of the ApplyRightsProtectionTemplate property. With this property, we assigned it the Encrypt template, which is the default encryption template.

Using this revised authentication method really simplified the task. We appreciate any further feedback that you may have. Thanks again!

**Comment by sehrish777** [comment]
Thanks. Below are our steps(lolz we have to go through a lengthy process):
1. 1. You should still be logged into LON-CL1 as the local **Admin** account, and in your Edge browser, you should still be logged into Microsoft 365 as **Holly Dickson**. 

1. 2. To open Windows PowerShell, enter **powershell** in the **Search** box on the taskbar. 

1. 3. In the menu that appears, right-click on **Windows PowerShell** and select **Run as administrator** in the drop-down menu. Run the below command in powershell and press enter:

```
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 3.1.0 -AllowClobber
```
>  If you are prompted to confirm, enter **A** to select **[A] Yes to All.** 

1. 4. In **Windows PowerShell**, you must begin by installing the **Microsoft Azure Active Directory Module for Windows PowerShell** by running the following command at the command prompt:

<br>

```
Install-Module MSOnline
```
	
1. 5. If you are prompted to install the **NuGet provider**, enter **Y** to select **[Y] Yes**. 

1. 6. If you are prompted to confirm whether you want to install the module from an untrusted repository (PSGallery), enter **A** to select **[A] Yes to All.** 

1. 7. Once the installation is complete, the screen will return to the command prompt. You must then run the following command to initiate a connection to Azure Active Directory: <br/>

```
Connect-ExchangeOnline -UserPrincipalName Holly@xxxxxZZZZZZ.onmicrosoft.com
```

> Where xxxxxZZZZZZ is the tenant prefix provided by your lab hosting provider

1. 8. A new window will appear requesting your credentials. Sign in as **Holly@xxxxxZZZZZZ.onmicrosoft.com** (where xxxxxZZZZZZ is the tenant prefix provided by your lab hosting provider) with a password of **User.pw1**.   
	
1. 9. Running unsigned PowerShell scripts from remote computers requires changing the execution policy for PowerShell. You should run the following command that changes the Execution Policy for this PC to **unrestricted**, which sets access to the external authorization for this PC so that it can connect to Microsoft online and load all configuration files and run all scripts:   <br/>

```
Set-ExecutionPolicy unrestricted
```

<br>
	
1. 10. If you are prompted whether you want to change the execution policy, enter **A** to select **[A] Yes to All**.
	
1. 11. A **Windows PowerShell credential request** window will appear. Sign in as **Holly@xxxxxZZZZZZ.onmicrosoft.com** (where xxxxxZZZZZZ is the tenant prefix provided by your lab hosting provider) and a password of **User.pw1**.  
	
1. 12. You must then run the following command to create a PSSession (titled $Session) that establishes a remote connection to Exchange Online through PowerShell. When you create a PSSession, Windows PowerShell establishes a persistent connection to the remote computer. Without the -Credential parameter that invokes the $Cred macro from the prior step, this command would prompt you for the credentials of the user authorizing this command. In this case, by invoking the $Cred macro, it applies Holly’s username and password.<br/>

```
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic -AllowRedirection
```
	
> **Note!** Since this feature is no longer supported, it is recommended to disregard any errors or warnings that may arise.  
	
1.  13. You should then run the following cmdlet to import commands, such as cmdlets, functions, and aliases, from the PSSession ($Session) created in the prior step. In this case, it imports the Exchange Online session into the PowerShell GUI. <br/>
```
Import-PSSession $Session
```

<br>
	
> **Note!** You can ignore the warning message that is displayed regarding unapproved verbs.  

1.  14. You will now create a mail flow rule by using the **New-TransportRule** cmdlet, and you will set the **ApplyOME** encryption parameter to $true. This rule will encrypt all outgoing mail from Adatum that is being sent to Gservices@adatum.com.  <br/>

To create this rule, run the following command:<br/>
```
New-TransportRule -Name "Encrypt rule for Guest Services" -SentTo "Gservices@adatum.com" -SentToScope "NotinOrganization" -ApplyOME $true
```
<br/>
	
> **Note!** This command will take several seconds to complete.

1.  15. To verify the rule exists, minimize your PowerShell window. In your Microsoft Edge browser, you should still be in the **mail flow** window of the **Exchange admin center**, and the **rules** tab should be displayed. The list of rules should only display the **Encrypt mail for guest@adatum.com** rule that you created in the prior task.<br/>

> On the menu bar that appears above the list of rules, select the **Refresh** icon. In the refreshed list, the rule that you just created using PowerShell should appear as well.
	
1. 16. Leave your browser session open for the next exercise.
