### ISSUE TITLE
Creating payloads has been moved to content library and is no longer available in Select payload and login page.

### ISSUE THREAD

**Issue by brookbeckertesting** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#155]
# Learning Path: 03
##### Step: 07

Description of issue
Creating payloads has been moved to content library and is no longer available in Select payload and login page. You must create it in the content library.

Repro steps:
Creating a payload is listed under step 7 as being under the simulation creation in the manual, but it's actually under Content library on the Attack Simulation training tab.

![image](https://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security/assets/94069201/855b3608-1482-4f07-b01e-846ef9c0d6b9)

![image](https://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security/assets/94069201/d0f1a68e-4516-4181-8d48-ba0b82d73ca4)

**Comment by tfrink** [comment]
Thank you for notifying us of this change. We have updated the lab instructions to create the payload first in the Content Library.
