### ISSUE TITLE
LAB_AK_01_Lab1_Ex1_Set_Up_Tenant.md - Unable to change Name of organization

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#158]
#### Step: 15

Description of issue

The option to change the Name is not editable. Is there any other way to update the name of the organization?

![image](https://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security/assets/98971092/e3dda325-c496-473a-9492-dfd2d4b2ea36)

**Comment by tfrink** [comment]
Hello Kiyani1,

I was unable to reproduce the issue you mentioned. I have opened VMs with several different tenants, including the one used in MS-101, and I was able to change the org name in all of them using the MOD Administrator account. See the following screen shot.

![org info page](https://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security/assets/12913870/46676bc1-765e-445f-968a-4800fcf1267e)

Please try this again to see if you can reproduce the issue.
