### ISSUE TITLE
Module 7 - Lab 7 - Exercise 2 - Implement Windows Information Protection

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#16]
# Module: 00
#### Step: 00

Description of issue
This lab needs a rewrite too the Intune Azure portal has gone - now needs updating for the endpoint.microsoft.com portal instead
Repro steps:

1.
1.
1.

**Comment by AustinP00** [comment]
I concur with this issue needing to be re-written. Attached is a text doc with corrected 
[LabProfile-83219-github-rewrite.txt](https://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security/files/5521731/LabProfile-83219-github-rewrite.txt)
instructions.

**Comment by tfrink** [comment]
The lab instructions have been updated as per the current update to the course that is releasing Nov 25th.
