### ISSUE TITLE
AIPInfoProtection.exe does not exist as a download anymore

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#17]
# Module: 7
## Lab/Demo: 7
##½ Exersize 1
#### Step: 6

This download does not exist anymore
What is the correct version to use?

Repro steps:

1.
1.
1.

**Comment by tfrink** [comment]
The lab instructions have been updated as per the current update to the course that is releasing Nov 25th.

**Comment by tfrink** [comment]
FYI - new file name is AIPUnifiedLabelClient.exe
