### ISSUE TITLE
"Client App" does not exist as a service name anymore in Azure Services

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#18]
# Module: 07
##### Step: 04-18

Description of issue
The Azure Service name (Client App) does not exist - 
and even if you find the functionality in Endpoint Policies - 
then nothing in the description fits the interface

This exercise needs a complete rewrite

**Comment by tfrink** [comment]
The lab instructions have been updated as per the current update to the course that is releasing Nov 25th.
