### ISSUE TITLE
Lab 3, Exercise 4

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#24]
# Module: 03
#### Step: 00

Description of issue
Lab steps do not match current portals

Repro steps:

Lab 3, Exercise 4, Task 2 is written with the legacy Exchange Admin center in mind. Steps 3 thru 9 need to either be prefaced by an instruction to click the 'Classic Exchange Admin Center' link (quick and dirty fix) or to be rewritten to work with the current EAC. Something similar to the below.

3. In the Exchange admin center, in the left-hand navigation pane, under recipients, click Mailboxes.
4. In the Mailboxes window, select Alex Wilber from the list of mailboxes.
5. Click the ellipsis (three dots) and then click 'Manage mailbox delegation'
6. To the right of 'Read and manage (0)', click Edit.
7. Click '+Add permissions'.
8. Check the box for Joni Sherman then click Save.

**Comment by geschwei** [comment]
Hi WigF1 this issue is resolved with the last pull requests.
