### ISSUE TITLE
Module 5, Lab 5, Exercise 2, Task 2

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#27]
# Module: 05
### Task: 02

Description of issue
The lab refers to the classic Exchange admin center and either needs a pointer to it or needs to be rewritten using the new Microsoft 365 Compliance center.

**Comment by MikeVeschi** [comment]
This hes yet to be updated. As stated here though MRM to Archive still needs to be in Exchange Classic as Compliance does not have Move to Archive.

"you should continue using messaging records management to move messages to archive mailboxes."
https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies

So this link should be made available in Task 2 Step 2 
USE Classic for retention to Archive 
https://outlook.office365.com/ecp/

**Comment by geschwei** [comment]
Due to the lab being specific to moving mail to the Archive folder. I have used Mike's suggestion and updated the lab accordingly.
