### ISSUE TITLE
MS-101 Mod11 Lab 10 Exercise 3 Task 5

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#33]
# Module: 11
#### Step: 27 (non existent step)

Delete Local Security Settings you just created,

When you run Notepad in Next Task 6 it says could not run app cause we just disabled default rules. So you can not get back into secpol to change it back it you exited prior. Can not proceed after this step.

VM Black on restart in LOD

**Comment by Michal-Ziemba** [comment]
Correct Task 5 as notepad was not included in the apps in the App protection policy and in Task 06 you can read as follows. 

**Task: 06**

[...] In this task, you will use Notepad. In a previous task, Notepad was included as one of the recommended apps in the App protection policy that you created. [...]

**Comment by geschwei** [comment]
Hello Michal and Mike, I'm trying to recreate the issue that you have found. Once I have successfully produced it, I will let you know of my findings.

**Comment by geschwei** [comment]
I have resolved this issue by having the students delete the created rules.
