### ISSUE TITLE
Module 11, Lab 10, Exercise 3, Task 4

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#35]
# Module: 11
#### Step: 05

Description of issue
Task 04 description says:

> This enables you to use Windows Information Protection (WIP) policies with Windows 10 apps to protect apps without device enrollment.

Step 05, last bullet should be corrected:
Enrollment state. **Without Enrollment**

**Comment by geschwei** [comment]
I am currently reviewing this issue.

**Comment by geschwei** [comment]
I have resolved this issue with the latest updates.
