### ISSUE TITLE
Brute Force and Spray attacks no longer an option

### ISSUE THREAD

**Issue by billwood44** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#38]
# Module: 03
#### Step: 00

Description of issue

The password brute force and spray attack simulations are no longer available in the portal.  This exercise needs to be removed from the lab.

Bill Wood, MCT, MCSE, MCSA

**Comment by geschwei** [comment]
Hi Billwood, I'm in the process of removing this lab and coming up with a suitable replacement.
