### ISSUE TITLE
MS-101 - Lab 2 Exercise 2 - Missing Users and Settings step in lab tasks

### ISSUE THREAD

**Issue by ivor-mct** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#43]
# Module: 02
#### Step: 09 and 10

There's an extra step that might not be picked up in the UI updates for Microsoft 365 Security and Compliance. The '**Users and Settings**' option to identify the users affected by the policy cannot be skipped and there's nothing indicated either on the GitHub copy nor the lab provider's (XtremeLabs) copy of the lab instructions.

**Comment by geschwei** [comment]
issue has been resolved. in the latest update.
