### ISSUE TITLE
Module 2 - Lab 2 - Exercise 1 Task 1 has not been updated

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#48]
Module 2 - Lab 2 - Exercise 1 Task 1

Step 2 Select Security, 
Step 3 Select Policies & Rules in Microsoft 365 Defender Portal then Select Threat Policies 

Step 9 In Domains add your tenant Domain name then click Next and select the Dynamic Delivery option

Step 10 Click Enable redirect

Remove steps 13 thru 16

Step 17 Review and Click Submit.

NOTE: If they students get errors they may need to run the Enable-OrganizationCustomization via Powershell with MOD admin account and wait about 10 Minutes to try again.
https://docs.microsoft.com/en-us/powershell/module/exchange/enable-organizationcustomization?view=exchange-ps

**Comment by geschwei** [comment]
resolved issue with the latest updates.
