### ISSUE TITLE
Module 2 - Lab 2 - Exercise 2 Task 1 UI Changes

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#49]
Module 2 - Lab 2 - Exercise 2 Task 1

Step 7  In Domains add your tenant Domain name then click Next 

Make current Step7, Step 8.

Eliminate Current Step 8 to Step 10

Step 9 Click Next

Step 10 Review Notification and Click Next

Step 11 Submit 

Step 12 Click Done

**Comment by geschwei** [comment]
resolved issue with the latest updates.
