### ISSUE TITLE
Microsoft 365 Compliance UI Change

### ISSUE THREAD

**Issue by StevenLODS** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#51]
# Module: 06
#### Step: 7 - 23

Looks like everything after step 6 has changed completely within Microsoft 365 Compliance > Data loss prevention > Create policy and no longer matches the instructional content provided.

**Comment by MikeVeschi** [comment]
This should be the new steps for this.
Module 6 - Lab 6 - Exercise 1 

Task 1

Step 3 takes you to Complaince Portal

Step 4 In Policies click + Create policy

Step 7 Unselect Devices, Microsoft Cloud App Security and On-premise repositories

Step 8 select Create otr customize and hit Next

Step 9 Create Rule, Name "Protect IP addresses"

Step 10 Click Add Condition , Click Content contains, Click Add

Step 11 Click Sensitive info types

Ste 12 and 13 proceed

Step 14 Click  + Add Condition, 

Step 15 Click Content is shared from Microsoft 365

Step 16 Turn User notification On

Step 17 (is Step 21) Turn on User Overrides 

Step 18 Click Save

Step 19 Click Next

Step 20-22 Turn on Right away

Step 23 Submit

**Comment by geschwei** [comment]
Thank you steven. i have resolved this issue with my latest update. thank you for bringing this to my attention.
