### ISSUE TITLE
Module 7 - Lab 7 - Exercise 1 - Step 37 38 and 39 conflicts with new Compliance Center settings

### ISSUE THREAD

**Issue by logandinesh** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#52]
# Module:07
##### Step: 38

Description of issue
Currently, the step mentioned as 
38 On the Policy settings page, select the Apply this label by default to documents and emails field, and in the drop-down menu that appears, select PII. Select the Users must provide justification to remove a label or lower classification label checkbox, and then select Next.

There is an extra step in between 37 and 38 let's say 37a, as follows
As soon as you complete step 37 and click Next we won't get the steps mentioned in step 38, what we get is 

On the Settings page > Policy settings > Configure settings for the labels included in this policy.
There are three options 

User must provide a justification to remove a label or lower its classification
Require users to apply a label to their emails and documents
Provide users with a link to a custom help page

Repro steps:
37. On the Publish to users and groups page, select Next.
37a. On the Settings page > Policy settings > Configure settings for the labels included in this policy windows, select the check box for User must provide a justification to remove a label or lower its classification  and click Next
![Mod7_lab7_Task1_Step37a](https://user-images.githubusercontent.com/53901216/125898295-906d0602-a755-482a-b7ab-d00d4ff2bf28.jpg)

38. Under Settings > Documents, on the apply a default label to the documents page in the drop-down menu that appears, select PII Click Next

38a. Under Settings > Emails, on the apply a default label to Emails page in the drop-down menu that appears, select PII and click Next
38b. Under Settings > PowerBI > Click next
![Mod7_lab7_Task1_Step38 38a 38b](https://user-images.githubusercontent.com/53901216/125898523-055c1958-5161-408a-9e32-a90cc415a720.jpg)

39. On the Name your policy page, enter PII Policy in the Name field and then enter (or copy and paste) the following description for this sensitivity label policy: The purpose of this policy is to detect sensitive information such as ABA bank routing numbers and US social security numbers in emails and documents and to encrypt this information when it's discovered. The user must provide an explanation for removing the classification label. Select Next.

**Comment by geschwei** [comment]
thank you for your feedback we will review the issue, and add the set of instructions.

**Comment by tfrink** [comment]
Thanks logandinesh! We have updated the instructions for this task per your recommendation. Thanks for catching this for us.
