### ISSUE TITLE
/LAB_AK_10_Lab9_Ex1_Device_Management.md - Licenses given inaccurate depending on Tenant used in course since original release

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#62]
# Module: 10
## Lab/Demo: 09
Exercise 01
#### Step: 04

Description of issue

In this step, it gives the total # of 'Enterprise Mobility + Security E5' licenses as 15, and references 15 licenses for 'Office 365 E5' however the total is actually 20 for each, and it is now 'Office 365 E3', not E5.

I believe this is as a result of the tenant originally specified changing since course release from 'M365 Enterprise' to a newer 'WWL M365 Enterprise 2019 w/ SPE_E'.  I am uncertain if the Tenant in use is always supposed to be identical between all ALHs, however.  (this may vary, and may not be of sufficient importance or commonality to be corrected.  Thus, just noting it as a potential issue and/or cause for student confusion.)

**Comment by geschwei** [comment]
This has been addressed with the latest pull request update.
